port: 7890
socks-port: 7891
allow-lan: true
mode: rule
log-level: info
ipv6: false

dns:
  enable: true
  listen: 0.0.0.0:5353
  ipv6: false
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  default-nameserver:
    - 114.114.114.114
    - 8.8.8.8
  nameserver:
    - https://doh.pub/dns-query
    - https://dns.google/dns-query

# CLASH САМ ЗАБИРАЕТ И ПЕРЕВУПАКОВЫВАЕТ ТВОИ СЕРВЕРА
proxy-providers:
  my_sub:
    type: http
    # Твоя ссылка, пропущенная через универсальный конвертер подписок
    url: "https://url.v1.mk/sub?target=clash&url=https://raw.githubusercontent.com/Cska90/my-vpn-sub/refs/heads/main/sub.txt"
    interval: 3600
    path: ./my_sub.yaml
    health-check:
      enable: true
      interval: 600
      url: http://cp.cloudflare.com/generate_204

proxy-groups:
  - name: 🚀 AUTO
    type: url-test
    use:
      - my_sub
    url: http://cp.cloudflare.com/generate_204
    interval: 300
    tolerance: 50

  - name: 🤖 AI
    type: select
    use:
      - my_sub
    proxies:
      - 🚀 AUTO
      - DIRECT

  - name: 🎬 MEDIA
    type: select
    use:
      - my_sub
    proxies:
      - 🚀 AUTO
      - DIRECT

  - name: 💬 SOCIAL
    type: select
    use:
      - my_sub
    proxies:
      - 🚀 AUTO
      - DIRECT

  - name: 🛡 VPN
    type: select
    use:
      - my_sub
    proxies:
      - 🚀 AUTO
      - DIRECT

  - name: 🌐 DIRECT
    type: select
    proxies:
      - DIRECT
      - 🚀 AUTO

rules:
  - DOMAIN-KEYWORD,openai,🤖 AI
  - DOMAIN-KEYWORD,anthropic,🤖 AI
  - DOMAIN-KEYWORD,claude,🤖 AI
  - DOMAIN-SUFFIX,chatgpt.com,🤖 AI
  - DOMAIN-KEYWORD,youtube,🎬 MEDIA
  - DOMAIN-SUFFIX,googlevideo.com,🎬 MEDIA
  - DOMAIN-SUFFIX,netflix.com,🎬 MEDIA
  - DOMAIN-SUFFIX,telegram.org,💬 SOCIAL
  - DOMAIN-SUFFIX,telegram.me,💬 SOCIAL
  - DOMAIN-SUFFIX,t.me,💬 SOCIAL
  - DOMAIN-SUFFIX,whatsapp.com,💬 SOCIAL
  - DOMAIN-SUFFIX,whatsapp.net,💬 SOCIAL
  - DOMAIN-KEYWORD,instagram,💬 SOCIAL
  - DOMAIN-KEYWORD,facebook,💬 SOCIAL
  - DOMAIN-KEYWORD,tiktok,💬 SOCIAL
  - DOMAIN-SUFFIX,twitter.com,💬 SOCIAL
  - DOMAIN-SUFFIX,x.com,💬 SOCIAL
  - DOMAIN-SUFFIX,4pda.to,🛡 VPN
  - DOMAIN-SUFFIX,4pda.ru,🛡 VPN
  - DOMAIN-SUFFIX,rutracker.org,🛡 VPN
  - DOMAIN-SUFFIX,rutor.info,🛡 VPN
  - DOMAIN-SUFFIX,rutor.org,🛡 VPN
  - DOMAIN-KEYWORD,nnmclub,🛡 VPN
  - MATCH,🌐 DIRECT
  
