port: 7890
socks-port: 7891
allow-lan: true
mode: rule
log-level: info
ipv6: false
dns:
  enable: true
  listen: 0.0.0.0:5353
  ipv6: false
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  default-nameserver:
  - 114.114.114.114
  - 8.8.8.8
  nameserver:
  - https://doh.pub/dns-query
  - https://dns.google/dns-query
proxies:
- name: Cska-Free
  type: vless
  server: 194.58.44.137
  port: 443
  uuid: b841ad3e-c26b-4fc8-acfc-810643d83633
  tls: true
  udp: true
  network: tcp
  servername: 194.58.44.137
  reality-opts:
    public-key: ''
    short-id: ''
  client-fingerprint: chrome
proxy-groups:
- name: 🚀 AUTO
  type: url-test
  proxies:
  - Cska-Free
  url: http://cp.cloudflare.com/generate_204
  interval: 300
  tolerance: 50
- name: 🤖 AI
  type: select
  proxies:
  - 🚀 AUTO
  - Cska-Free
  - DIRECT
- name: 🎬 MEDIA
  type: select
  proxies:
  - 🚀 AUTO
  - Cska-Free
  - DIRECT
- name: 💬 SOCIAL
  type: select
  proxies:
  - 🚀 AUTO
  - Cska-Free
  - DIRECT
- name: 🛡 VPN
  type: select
  proxies:
  - 🚀 AUTO
  - Cska-Free
  - DIRECT
- name: 🌐 DIRECT
  type: select
  proxies:
  - DIRECT
  - 🚀 AUTO
rules:
- DOMAIN-KEYWORD,openai,🤖 AI
- DOMAIN-KEYWORD,anthropic,🤖 AI
- DOMAIN-KEYWORD,claude,🤖 AI
- DOMAIN-SUFFIX,chatgpt.com,🤖 AI
- DOMAIN-KEYWORD,youtube,🎬 MEDIA
- DOMAIN-SUFFIX,googlevideo.com,🎬 MEDIA
- DOMAIN-SUFFIX,netflix.com,🎬 MEDIA
- DOMAIN-SUFFIX,telegram.org,💬 SOCIAL
- DOMAIN-SUFFIX,telegram.me,💬 SOCIAL
- DOMAIN-SUFFIX,t.me,💬 SOCIAL
- DOMAIN-SUFFIX,whatsapp.com,💬 SOCIAL
- DOMAIN-SUFFIX,whatsapp.net,💬 SOCIAL
- DOMAIN-KEYWORD,instagram,💬 SOCIAL
- DOMAIN-KEYWORD,facebook,💬 SOCIAL
- DOMAIN-KEYWORD,tiktok,💬 SOCIAL
- DOMAIN-SUFFIX,twitter.com,💬 SOCIAL
- DOMAIN-SUFFIX,x.com,💬 SOCIAL
- DOMAIN-SUFFIX,4pda.to,🛡 VPN
- DOMAIN-SUFFIX,4pda.ru,🛡 VPN
- DOMAIN-SUFFIX,rutracker.org,🛡 VPN
- DOMAIN-SUFFIX,rutor.info,🛡 VPN
- DOMAIN-SUFFIX,rutor.org,🛡 VPN
- DOMAIN-KEYWORD,nnmclub,🛡 VPN
- MATCH,🌐 DIRECT
