name: Build Clash Config

on:
  push:
    paths:
      - 'sub.txt'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create config file
        run: |
          echo "# generated automatically" > config.yaml

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add config.yaml
          # Проверка на изменения
          if ! git diff --cached --quiet; then
            git commit -m "Update config.yaml"
            git push
          else
            echo "No changes to commit"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
